name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Compile program and create build folder
      run: make install

    - name: Compile and run tests
      run: make run_tests

    - name: Clean generated files and directories
      run: make clean 
